version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  make-new-release:
    docker:
      - image: cimg/python:3.8.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - install-gh-cli
      - run:
          name: Create release
          command: |
            RELEASE_VERSION=$(poetry version --short)
            gh release create $RELEASE_VERSION --generate-notes

workflows:
  main:
    jobs:
      - make-new-release:
          filters:
            branches:
              only:
                - master
                - main
          context:
            - GITHUB_CREDS

commands:
  install-gh-cli:
    description: Install Github CLI
    steps:
      - run:
          name: Get and install gh-cli
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
